### ISSUE TITLE
disabling sublimation on scholar is completely undocumented

### ISSUE THREAD

**Issue by ChristopherJTrent** [cyritegamestudios/trust#101]
I really *really* don't want my BLU/SCH using sublimation, ever. Your docs don't say how to turn off sublimation, and it's not present at all in the config file. What am I expected to do in this situation?

**Comment by cyrite** [comment]
Hey @ChristopherJTrent, it's part of the base job logic and not possible to configure currently, however if you'd like to manually disable it you can comment out this [line](https://github.com/cyritegamestudios/trust/blob/8fc0dd15d04a4532dac4214c4ba7dfdbc31b1bfe/cylibs/trust/data/SCH.lua#L88) like this `-- self:check_sublimation()` and then reload Trust with `// lua r trust`.

Please note this will prevent Sublimation from being used at all, even when Scholar is set to the main job. If you want to re-enable it, you will have to uncomment the line above by removing the `--` and reload Trust again. I'll consider adding a new mode for this in the future.

Cheers!

**Comment by cyrite** [comment]
Fixed in v10.0.0.
