### ISSUE TITLE
Rdm Composure

### ISSUE THREAD

**Issue by Chrollor** [cyritegamestudios/trust#117]
Everything is working great on this addon with the exception of Composure for Rdm.    Any suggestions would be helpful.    Big props to you for creating this, thank you so much love this addon.

**Comment by cyrite** [comment]
Glad you like it! I would probably need more information to help, but here are a few things to check:
1. Ensure both the GearSwap and Shortcuts add-ons are loaded with no errors
2. Ensure `Composure` is selected in the Trust UI under `Settings > Buffs > Abilities`
3. Ensure `AutoBuffMode` is set to `Auto`
4. If the above doesn't work, try manually deleting `addons/trust/data/RDM_PlayerName.lua` and reloading trust with `// lua r trust` to generate a new one.

You can also hop over to the [Cyrite Game Studios Discord](https://discord.gg/CfPxDy759J) and we can debug it there!
