### ISSUE TITLE
Blue Spell

### ISSUE THREAD

**Issue by Makiavelli2** [cyritegamestudios/trust#135]
Blue spell is doing the same thing like the Ninja utsusemi before it got fix 
I use Blue as sub job so I don't know if that is the case or the reason why it's not letting me add the spell.
This is with latest version v9.5.2 . I know it was working on version 8.8.6. and I notice after that it's been broken ever since.

**Comment by cyrite** [comment]
You have to have the spells equipped *before* loading Trust. Did you try that and does it still not work?

**Comment by Makiavelli2** [comment]
as far as having the spell like Cocoon yea this is what I see when I load it 
![Screenshot 2024-07-15 165455](https://github.com/user-attachments/assets/f7b944ff-889f-40d7-afb7-e37c7a87cf1d)
and this is what I see when click add 
![empty](https://github.com/user-attachments/assets/dc829cae-0e62-4589-ba73-922dcb6eed44)

**Comment by cyrite** [comment]
Can you show me your Blue Magic spell menu?

**Comment by cyrite** [comment]
Ah sorry I missed the part about sub job. Yeah I don't think the UI currently works for adding Blue Magic subs when Blue Mage is your sub job. Try switching to main job first and doing it that way for now.

**Comment by cyrite** [comment]
I'll add a fix for this in the next release.

**Comment by cyrite** [comment]
Fixed in v10.0.0.
