### ISSUE TITLE
The pull list for mobs doesn't clear

### ISSUE THREAD

**Issue by Makiavelli2** [cyritegamestudios/trust#171]

**Comment by cyrite** [comment]
@Makiavelli2 which version of Trust are you running?

**Comment by Makiavelli2** [comment]
I'm running the v10.4.4 
Main job is sam and subjob is war

**Comment by cyrite** [comment]
Check out this thread and see if it fixes your issue: https://discord.com/channels/1069136494616399883/1261741862826545182

**Comment by cyrite** [comment]
tl;dr try removing (or make a backup copy of) `addons/trust/data/settings.xml` and running `// lua r trust`.

**Comment by Makiavelli2** [comment]
Sorry I just notice some one already posted about this I tried deleting the setting.xml and it's a same thing.

**Comment by cyrite** [comment]
Did this only just start happening or always happened? What operating system are you running? Send me your settings.xml file on Discord. The only other thing I can think of is to re-install Trust:
1. Save your `addons/trust/data` folder so you can recover your settings afterwards
2. Delete `addons/trust`
3. Download the latest release

**Comment by cyrite** [comment]
Or another alternative, edit the `addons/trust/data/settings.xml` manually to add/remove the mob names, though that shouldn't be necessary. I suspect either 1) your Trust install got corrupted somehow or 2) your mob list in settings.xml is formatted incorrectly or has some weird encoding.

**Comment by Makiavelli2** [comment]
yeah editing the xml removing mobs manually  fix it now the mob can be add on or remove weird lol thank you!

**Comment by cyrite** [comment]
Very odd, but glad it works now!
