### ISSUE TITLE
Dark Knight Entropy Randomly goes off

### ISSUE THREAD

**Issue by Makiavelli2** [cyritegamestudios/trust#186]
with the latest version v10.6.5 on DRK Entropy Goes off randomly even though its black listed and not on skillchain list.

**Comment by cyrite** [comment]
This behavior is caused by `AutoRestoreManaMode`. You can disable it by setting it to `Off` either in the menu or with `// trust set AutoRestoreManaMode Off` and saving.

**Comment by Makiavelli2** [comment]
ah got it  thank you
