### ISSUE TITLE
Not engaging after some pull

### ISSUE THREAD

**Issue by Makiavelli2** [cyritegamestudios/trust#295]
there is an issue where after a while it will stop engaging but it will still buff itself and do debuff, I just notice this on the last two latest release [v12.7.4] and [v12.7.5]

**Comment by cyrite** [comment]
Hi! Can you share a few more details:
1. Who is not engaging? Is it your puller or someone assisting the puller?
2. If you just leave it, does it never engage? Or does it engage after it finishes buffing?
3. Can you [share your profile](https://github.com/cyritegamestudios/trust/wiki/Profiles#share-a-profile)?

**Comment by Makiavelli2** [comment]
my main toon and it will not engage it will just stand there and will use debuff and buff it self .
I'm not sure what you mean by proifile do u mean under the data folder? this is on my rdm/nin  by the way I don't know if it happen to other job.

**Comment by cyrite** [comment]
You can share it in the [Discord](https://discord.gg/CfPxDy759J).

**Comment by Makiavelli2** [comment]
ok I downloaded the latest version v12.8.2 started clean install and now it's working fine I guess it had to do with the profile or something going wrong with data folder. I just use the updating tool you provided to update the trust. It seems that this becoming a problem after some major update and to fix it is just to start clean install. but any who thanks for the reply.
