### ISSUE TITLE
//trust assist <Name> doesn't get save after zoning

### ISSUE THREAD

**Issue by momotaroko** [cyritegamestudios/trust#3]
Whenever I do //trust assist <Name>, it saves and assist the character correctly then i do //trust save, but then whenever I zone, I do //trust status and it assist itself. The name that I had set to assist has been reset.

**Comment by cyrite** [comment]
I think I implemented it that way on purpose, but I can't remember why. You're correct that // trust assist doesn't currently save between zoning but it could be added fairly easily by saving it to Trust/data/settings.xml.

**Comment by cyrite** [comment]
@momotaroko this is the line that reset it when you zone: https://github.com/cyritegamestudios/trust/blob/04d1fd012d15503279f284cbd22da6f545c3c6fd/addons/Trust/Trust.lua#L325

You could try commenting that out and see if it doesn't cause other issues. It still won't save between reloads of the Trust add-on, though.

**Comment by cyrite** [comment]
Fixed now!
