### ISSUE TITLE
Auto executed functions fail due to numeric string on command line

### ISSUE THREAD

**Issue by lcreed** [cyritegamestudios/trust#87]
![image](https://github.com/cyritegamestudios/trust/assets/734957/915f9042-80fc-4974-8d9f-a8e33a77a040)

**Comment by cyrite** [comment]
@lcreed Trust currently requires Shortcuts and GearSwap (https://github.com/cyritegamestudios/trust#dependencies). Making sure you have a version of those running should fix your issue!

**Comment by lcreed** [comment]
that was the issue.  Thanks!
